# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html

image: node:6.11.1

cache:
  paths:
   - node_modules/

before_script:
  - yarn install

pages:
  stage: deploy
  script:
  - gulp
  - mkdir public
  - cp -r dist/* public
  - cp index.html public
  - lftp sftp://$USERNAME:$PASSWORD@$HOST -e "mirror -Rev dist/ /home/webuser/bid/www/www/images/icons/.  --ignore-time --parallel=10/;quit;"
  artifacts:
    paths:
    - public
  only:
  - master